dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: golang-http-jxboot-20200220003
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
